###

POST https://health-tracking-system.azurewebsites.net/api/admin/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin123"
}

###

POST https://health-tracking-system.azurewebsites.net/api/admin/register
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@gmail.com",
    "password": "admin123"
}